### ISSUE TITLE
Allow to change I2C address of the sensor

### ISSUE THREAD

**Issue by nathanmutin** [REVrobotics/2m-Distance-Sensor#5]
It would be cool if we could change the I2C address of the sensor so it would be possible to use several of them.
There is a function called [VL53L0X_SetDeviceAddress](https://github.com/REVrobotics/2m-Distance-Sensor/blob/master/Source/src/main/native/include/vl53l0x_api.h#L362) that seems to allow to do it.

**Comment by willtoth** [comment]
I definitely understand the desire to do this especially for cases where you would want multiple of the same device on the bus. The problem is the change does not persist power cycles. So if you had two sensors on the bus, how would you send the 'set address' command to only one of them?

I'm not opposed to adding it, I just am not sure that it has much value since it does not persist.

**Comment by nathanmutin** [comment]
Ok, I didn't know it. You're right if it does not persist I don't see the case where it would be useful.
